"""Initial Migration 2

Revision ID: 778f9fa05ce7
Revises: 75b670072e37
Create Date: 2026-01-07 17:30:07.980580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778f9fa05ce7'
down_revision: Union[str, Sequence[str], None] = '75b670072e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skins_owner_id_fkey'), 'skins', type_='foreignkey')
    op.drop_column('skins', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('skins_owner_id_fkey'), 'skins', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
