"""initial migration

Revision ID: 8654a14d0f5b
Revises: 15480d24a459
Create Date: 2026-01-03 17:27:54.076637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8654a14d0f5b'
down_revision: Union[str, Sequence[str], None] = '15480d24a459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserInventory', sa.Column('is_on_discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserInventory', 'is_on_discount')
    # ### end Alembic commands ###
