"""Initial Type_weapon

Revision ID: d4d1b114e7fb
Revises: d92e611c45a5
Create Date: 2026-01-12 21:57:39.916732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d1b114e7fb'
down_revision: Union[str, Sequence[str], None] = 'd92e611c45a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('type_weapon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'type_weapon')
    # ### end Alembic commands ###
