"""Initial fix balance 2

Revision ID: d92e611c45a5
Revises: 9aa440d990f3
Create Date: 2026-01-11 14:45:14.445330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92e611c45a5'
down_revision: Union[str, Sequence[str], None] = '9aa440d990f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
